pipeline:
  name: ci-pipeline
  identifier: cipipeline
  projectIdentifier: SAMPLE
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Gitconnectoradmin
        repoName: supermariocp
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: minikube
              namespace: nonprod
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Gitconnectoradmin
                    repoName: supermariocp
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.Docker
                    repo: fardeenattar/mario-image
                    tags:
                      - <+timestamp>
                    caching: false
                  outputVariables:
                    - name: imageTag
                      type: String
                      value: <+timestamp>
              - step:
                  type: Run
                  name: UpdateGitOpsManifest
                  identifier: UpdateGitOpsManifest
                  spec:
                    connectorRef: account.Docker
                    image: alpine/git
                    shell: Sh
                    command: |-
                      #!/bin/sh

                      # Clone the private manifest repo using Harness GitHub Token secret
                      git clone https://<+secrets.getValue("account.aws-cf-token")>@github.com/Fardeen313/Mario-game-manifest.git

                      cd Mario-game-manifest || exit 1

                      # ✅ Replaced placeholder with actual output path to tag
                      sed -i "s|fardeenattar/mario-image:.*|fardeenattar/mario-image:<+pipeline.stages.build.spec.execution.steps.BuildAndPushDockerRegistry_1.output.imageTag>|" mario.yml

                      git config --global user.email "bot@harness.io"
                      git config --global user.name "harness-bot"

                      git add .
                      # ✅ Same change in commit message
                      git commit -m "CI: update image tag to <+pipeline.stages.build.spec.execution.steps.BuildAndPushDockerRegistry_1.output.imageTag>" || echo "Nothing to commit"
                      git push origin main
