pipeline:
  name: ci-pipeline
  identifier: cipipeline
  projectIdentifier: SAMPLE
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Gitconnectoradmin
        repoName: supermariocp
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: minikube
              namespace: nonprod
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Gitconnectoradmin
                    repoName: supermariocp
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Set Image Tag
                  identifier: Set_Image_Tag
                  spec:
                    connectorRef: account.Docker
                    image: alpine:latest
                    shell: Sh
                    command: |
                      export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
                      echo "IMAGE_TAG=$IMAGE_TAG" >> harness/env.properties
                  outputVariables:
                    - name: IMAGE_TAG
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.Docker
                    repo: fardeenattar/mario-image
                    tags:
                      - <+pipeline.stages.build.spec.execution.steps.Set_Image_Tag.output.IMAGE_TAG>
                    caching: false
              - step:
                  type: Run
                  name: UpdateGitOpsManifest
                  identifier: UpdateGitOpsManifest
                  spec:
                    connectorRef: account.Docker
                    image: alpine/git
                    shell: Sh
                    command: |-
                      #!/bin/sh

                      git clone https://<+secrets.getValue("account.aws-cf-token")>@github.com/Fardeen313/Mario-game-manifest.git
                      cd Mario-game-manifest || exit 1

                      sed -i "s|fardeenattar/mario-image:.*|fardeenattar/mario-image:<+pipeline.stages.build.spec.execution.steps.Set_Image_Tag.output.IMAGE_TAG>|" mario.yml

                      git config --global user.email "bot@harness.io"
                      git config --global user.name "harness-bot"

                      git add .
                      git commit -m "CI: update image tag to <+pipeline.stages.build.spec.execution.steps.Set_Image_Tag.output.IMAGE_TAG>" || echo "Nothing to commit"
                      git push origin main
