# name: CI Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     env:
#       IMAGE_NAME: fardeenattar/mario-image

#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v3

#       - name: Set Docker image tag (timestamp-based)
#         run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_TOKEN }}

#       - name: Build and push Docker image
#         run: |
#           docker build -t $IMAGE_NAME:$IMAGE_TAG .
#           docker push $IMAGE_NAME:$IMAGE_TAG

#       - name: Clone manifests repo
#         env:
#           GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
#         run: |
#           git clone https://x-access-token:${GH_TOKEN}@github.com/Fardeen313/kube-main.git
#           cd kube-main/day-5-ingress/

#           # Update the image tag in deployment manifest
#           sed -i "s|fardeenattar/mario-image:.*|fardeenattar/mario-image:$IMAGE_TAG|g" mario.yml

#           # Commit and push the change
#           git config user.name "github-actions"
#           git config user.email "github-actions@github.com"
#           git commit -am "CI: update image tag to $IMAGE_TAG"
#           git push
name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: fardeenattar/mario-image

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set Docker image tag (timestamp-based)
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Clone manifests repo
        env:
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/Fardeen313/Mario-game-manifest.git
          cd Mario-game-manifest/

          # Update the image tag in deployment manifest
          sed -i "s|fardeenattar/mario-image:.*|fardeenattar/mario-image:$IMAGE_TAG|g" mario.yml

          # Commit and push the change
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "CI: update image tag to $IMAGE_TAG"
          git push
